[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cycles=auto

[mixer]
nosound=false
rate=22050
blocksize=2048
prebuffer=10

[autoexec]
mount c .
C:
CD \
PRINCE.EXE
